AllCops:
  TargetRubyVersion: 2.7

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Severity: warning
  Max: 120

Metrics/BlockLength:
  Severity: warning
  Exclude: ["**/*_spec.rb"]

Style/Documentation:
  Severity: warning
  AllowedConstants: ['ClassMethods']
